spring:
  profiles:
    default: local
  docker:
    compose:
      enabled: false

server:
  shutdown: graceful

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  override-with-generic-response: true

oauth:
  facebook:
    client-id: 1279366430568673
    client-secret: ${FACEBOOK_OAUTH_SECRET}
    callback-uri: https://api.do-doodle.com/auth/facebook/callback
  kakao:
    client-id: FIXME
    callback-uri: FIXME

aws:
  s3:
    access-key: FIXME
    secret-key: FIXME
    region: kr-standard
    bucket-name: dodoodle
    endpoint: https://kr.object.ncloudstorage.com
