spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drawit
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

  docker:
    compose:
      enabled: false

biz:
  notification-channel:
    error-message: https://discord.com/api/webhooks/1391033359358234734/DiF2dBjekTaOVhf8PQuB9dK3Dxyps5dtmtHgo_XuqaBb4Ls1N45raYoG-CYCA_SvA61H
    etc-message: https://discord.com/api/webhooks/1391033359358234734/DiF2dBjekTaOVhf8PQuB9dK3Dxyps5dtmtHgo_XuqaBb4Ls1N45raYoG-CYCA_SvA61H
