spring:
  profiles:
    default: local
  docker:
    compose:
      enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
server:
  shutdown: graceful

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  override-with-generic-response: true

oauth:
  facebook:
    client-id: 1279366430568673
    client-secret: ${FACEBOOK_OAUTH_SECRET}
    callback-uri: ${FACEBOOK_OAUTH_CALLBACK_URI}
  kakao:
    client-id: ${KAKAO_OAUTH_CLIENT_ID}
    callback-uri: ${KAKAO_OAUTH_CALLBACK_URI}

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: kr-standard
    bucket-name: dodoodle
    endpoint: https://kr.object.ncloudstorage.com
