spring:
  profiles:
    default: local
  docker:
    compose:
      enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
server:
  shutdown: graceful

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  override-with-generic-response: true

oauth:
  facebook:
    client-id: ${FACEBOOK_OAUTH_CLIENT_ID}
    client-secret: ${FACEBOOK_OAUTH_SECRET}
    callback-uri: ${FACEBOOK_OAUTH_CALLBACK_URI}
  kakao:
    client-id: ${KAKAO_OAUTH_CLIENT_ID}
    callback-uri: ${KAKAO_OAUTH_CALLBACK_URI}
  google:
    client-id: ${GOOGLE_OAUTH_CLIENT_ID}
    client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
    callback-uri: ${GOOGLE_OAUTH_CALLBACK_URI}

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: kr-standard
    bucket-name: dodoodle
    endpoint: https://kr.object.ncloudstorage.com

llm:
  openai:
    api-key: ${OPENAI_API_KEY}

biz:
  notification-channel:
    error-message: ${DISCORD_ERROR_WEBHOOK_URL}
    etc-message: ${DISCORD_ETC_WEBHOOK_URL}
    metrics-message: ${DISCORD_METRICS_WEBHOOK_URL}