spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-server:3306/drawit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  docker:
    compose:
      enabled: false

biz:
  notification-channel:
    error-message: ${NOTIFICATION_CHANNEL}
    etc-message: ${NOTIFICATION_CHANNEL}

aws:
  s3:
    phase: prod
