#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://FIXME/drawit
#    username: FIXME
#    password: FIXME
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        highlight_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: info
        type.descriptor.sql: info

biz:
  notification-channel:
    error-message: https://discord.com/api/webhooks/1391033359358234734/DiF2dBjekTaOVhf8PQuB9dK3Dxyps5dtmtHgo_XuqaBb4Ls1N45raYoG-CYCA_SvA61H
    etc-message: https://discord.com/api/webhooks/1391033359358234734/DiF2dBjekTaOVhf8PQuB9dK3Dxyps5dtmtHgo_XuqaBb4Ls1N45raYoG-CYCA_SvA61H
