name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build Docker image with Jib
        run: ./gradlew jibDockerBuild

      - name: Save Docker image as tar
        run: |
          docker save draw-it-api:latest -o draw-it-api.tar
          chmod 644 draw-it-api.tar

      - name: Copy image to EC2 and deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          password: ${{ secrets.EC2_PASSWORD }}
          source: "draw-it-api.tar"
          target: "/tmp/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop draw-it-api || true
            docker rm draw-it-api || true
            docker rmi draw-it-api:latest || true
            docker load -i /tmp/draw-it-api.tar
            docker run -d --name draw-it-api --env-file /root/.env -p 8080:8080 draw-it-api:latest
            rm /tmp/draw-it-api.tar