name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build Docker image with Jib
        run: ./gradlew jibDockerBuild

      - name: Save Docker image as tar
        run: |
          docker save draw-it-api:latest -o draw-it-api.tar
          chmod 644 draw-it-api.tar

      - name: Copy image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          password: ${{ secrets.EC2_PASSWORD }}
          source: "draw-it-api.tar"
          target: "/tmp/"

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 기존 컨테이너 종료
            cd /root
            docker-compose down || true
            
            # 기존 이미지 제거
            docker rmi draw-it-api:latest || true
            
            # 새 이미지 로드
            docker load -i /tmp/draw-it-api.tar
            
            # Docker Compose로 서비스 시작
            docker-compose up -d
            
            # 임시 파일 정리
            rm /tmp/draw-it-api.tar
            
            # 배포 상태 확인
            docker-compose ps